modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"
[[mods]]
	modId="carbonconfig"
	version="${file.jarVersion}"
	displayName="Carbon Config Library"
	displayURL="https://github.com/Carbon-Config-Project/CarbonConfig"
	logoFile="carbonconfig.png"
	credits="Thanks to the IC2Classic team for open sourcing this"
	authors="Meduris, Speiger"
	description='''
		Carbon Config is IC2Classics Config Implementation made open source
	'''
	[[dependencies.carbonconfig]]
		modId="neoforge"
		required=true
		versionRange="[21.0.143,)"
		ordering="NONE"
		side="BOTH"
	[[dependencies.carbonconfig]]
		modId="minecraft"
		required=true
		versionRange="[1.21,)"
		ordering="NONE"
		side="BOTH"